#!/usr/bin/perl

@DIRS_TO_PROCESS = `ls -d /SGE_RAID/RESSLER_TRAUMA_IMAGING/RESIL*`;


my %SUBJECT_ASSIGNMENTS;

$SUBJECT_ASSIGNMENTS{"6610"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"6753"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"6824"} = "PTSD";
###$SUBJECT_ASSIGNMENTS{"7293"} = "TRAUMA_ONLY"; Patient not used-- panic attack in scan room

$SUBJECT_ASSIGNMENTS{"7373"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"7422"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"7464"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"7470"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"7555"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"7591"} = "EXCLUDED";   ## JUNK-- is justine's brain!
$SUBJECT_ASSIGNMENTS{"7614"} = "EXCLUDED";  ### EXCLUDED FOR SUBDURAL HEMATOMA!! was A PTSD
$SUBJECT_ASSIGNMENTS{"7618"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"7806"} = "TRAUMA_ONLY";

$SUBJECT_ASSIGNMENTS{"7807"} = "PTSD";
$SUBJECT_ASSIGNMENTS{"7810"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"8025"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"8155"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"8178"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"8382"} = "PTSD";
$SUBJECT_ASSIGNMENTS{"8383"} = "PTSD";
$SUBJECT_ASSIGNMENTS{"8489"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"8453"} = "EXCLUDED"; ## PTSD patient.. NO DTI DATA
$SUBJECT_ASSIGNMENTS{"8489"} = "PTSD"; 


$SUBJECT_ASSIGNMENTS{"8496"} = "EXCLUDED"; #"TRAUMA_CTRL"; ## NO DTI DATA



$SUBJECT_ASSIGNMENTS{"8518"} = "TRAUMA_ONLY";

$SUBJECT_ASSIGNMENTS{"8543"} = "PTSD";
$SUBJECT_ASSIGNMENTS{"8593"} = "EXCLUDED"; #"PTSD"; NO DTI DATA
$SUBJECT_ASSIGNMENTS{"8595"} = "PTSD";


$SUBJECT_ASSIGNMENTS{"8798"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"8855"} = "TRAUMA_ONLY";  




$SUBJECT_ASSIGNMENTS{"8857"} = "TRAUMA_ONLY";  ## LOTS OF MOVEMENT
$SUBJECT_ASSIGNMENTS{"8871"} = "TRAUMA_ONLY";

$SUBJECT_ASSIGNMENTS{"8883"} = "TRAUMA_ONLY";


$SUBJECT_ASSIGNMENTS{"8897"} = "TRAUMA_ONLY";


$SUBJECT_ASSIGNMENTS{"8982"} = "EXCLUDED"; #"TRAUMA_ONLY";  ### INCOMPLETE DTI DATA?? rmoved from scanner during scan
$SUBJECT_ASSIGNMENTS{"8985"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"8993"} = "TRAUMA_ONLY";
$SUBJECT_ASSIGNMENTS{"9005"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"9035"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"9080"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"9083"} = "EXCLUDED"; ## NO DTI DATA


$SUBJECT_ASSIGNMENTS{"9176"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"9185"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"9233"} = "PTSD";

$SUBJECT_ASSIGNMENTS{"9268"} = "EXCLUDED"; ## NO DTI DATA

$SUBJECT_ASSIGNMENTS{"9295"} = "EXCLUDED"; #@"PTSD";  ## STOPPED IN MID RUN


$PTSD_GROUP=0;
$CTRL_GROUP=0;
$TOTAL_PATIENTS = 0;
$EXCLUDED = 0;

foreach $subj_key ( keys %SUBJECT_ASSIGNMENTS )
	{
	$TOTAL_PATIENTS++;
	if($SUBJECT_ASSIGNMENTS{$subj_key} eq "TRAUMA_ONLY") { $CTRL_GROUP++;}
	elsif($SUBJECT_ASSIGNMENTS{$subj_key} eq "PTSD") { $PTSD_GROUP++;}
	elsif($SUBJECT_ASSIGNMENTS{$subj_key} eq "EXCLUDED") { $EXCLUDED++;}
		
}
print "There are $PTSD_GROUP ptsd patients and $CTRL_GROUP control patients exlcued $EXCLUDED and $TOTAL_PATIENTS total patients... \n";



$TBSS_OUTPUT_DIR = "/SGE_RAID/RESSLER_TRAUMA_IMAGING/DATA_ANALYSIS/my_tbss_35subjs/";
$TBSS_MD_OUTPUT_DIR = "/SGE_RAID/RESSLER_TRAUMA_IMAGING/DATA_ANALYSIS/my_tbss_MD_35subjs/";



### CREATE OUTPUT DIRECTORIES
if( ! -d $TBSS_OUTPUT_DIR) { `mkdir $TBSS_OUTPUT_DIR`;}


if( ! -d $TBSS_MD_OUTPUT_DIR) { `mkdir $TBSS_MD_OUTPUT_DIR`;}



### I AM GOING TO REAPPLY THE MASK FROM THE MANUAL_BET directory and then copy over this newly generated image to the struc directory



for($i=0;$i<=$#DIRS_TO_PROCESS;$i++)
	{
## ITERATING THROUGH ALL DIRECTORIES AND WILL COPY FILES AS NEEDED
	$CURRENT_DIRECTORY = $DIRS_TO_PROCESS[$i];
	chomp($CURRENT_DIRECTORY);
$CURRENT_DIRECTORY =~ m/(.*)_Subject_(\d+)/;
#print "Processing $CURRENT_DIRECTORY ...subject $2 \n";


$CURRENT_SUBJECT_ID = $2;

$GROUP_ID_TAG = $SUBJECT_ASSIGNMENTS{$CURRENT_SUBJECT_ID};  

if($GROUP_ID_TAG eq "TRAUMA_ONLY" || $GROUP_ID_TAG eq "PTSD") 
	{


print "Current subject tag is :$CURRENT_SUBJECT_ID:$GROUP_ID_TAG\n";

$statement = " cp $CURRENT_DIRECTORY" . "/dti_data/data_FA.nii.gz " . $TBSS_OUTPUT_DIR  . $GROUP_ID_TAG . "-$2" . "_dti_data.nii.gz";
#print $statement . "\n";
`$statement`;


$statement = " cp $CURRENT_DIRECTORY" . "/dti_data/data_MD.nii.gz " . $TBSS_MD_OUTPUT_DIR  . $GROUP_ID_TAG . "-$2" . "_dti_data_MD.nii.gz";
#print $statement . "\n";
`$statement`;





	}
elsif( $GROUP_ID_TAG eq "EXCLUDED")
	{
	print "Excluded $CURRENT_SUBJECT_ID \n";
	}

else	{

print  "This is either an unknown subject ID or you have decided to exclude it..... for $CURRENT_SUBJECT_ID ... \n";
	}


	}

exit;

`cp /SGE_RAID/RESSLER_TRAUMA_IMAGING/DATA_ANALYSIS/my_tbss/*.nii.gz /var/www/RESSLER_IMAGING/TBSS_PIPELINE/`;

$output_dir = "/var/www/RESSLER_IMAGING/TBSS_PIPELINE/";
chdir $output_dir;
`slicesdir *.nii.gz`;



